"""Generate the small 16x16 Chinese font subset used by the TFT report page."""

from pathlib import Path
import re

from PIL import Image, ImageDraw, ImageFont


FONT_PATH = Path(r"C:\Windows\Fonts\msyh.ttc")
OUTPUT_PATH = Path(__file__).resolve().parents[1] / "main" / "chinese_font_16.h"

# Keep this in sync with the constrained DeepSeek report vocabulary.
CHARACTERS = (
    "分析建议结论新鲜度风险高低中油桃四个检测面整体稳定"
    "未发现明显异常存在差异局部腐坏概率较请检查软烂异味"
    "渗液霉斑尽快食用不要继续存放如有应丢弃当前状态良好"
    "可短期冷藏保存并优先结果显示下降依据最高位置平均综合"
    "判断模型仅供参考结合外观触感确认第处中文报告预警"
    "准备就绪等待开始请将放在按面对准传感器合适后正在进度"
    "保持静止调整到完成本先移开移出范围再换旋转好继续平均"
    "最高云端智能稍候连接失败检查网络重试服务配置请求提交"
    "优先下一取消数据置信需要关注生成系统自动厘米"
    "等趋势升或前地已时标目离距采集"
    "辅助边缘断网一致点"
    "，。；：、"
)


def glyph_bitmap(character: str) -> list[int]:
    font = ImageFont.truetype(str(FONT_PATH), 16)
    image = Image.new("1", (16, 16), 0)
    draw = ImageDraw.Draw(image)
    left, top, right, bottom = draw.textbbox((0, 0), character, font=font)
    x = (16 - (right - left)) // 2 - left
    y = (16 - (bottom - top)) // 2 - top
    draw.text((x, y), character, font=font, fill=1)

    output: list[int] = []
    for row in range(16):
        for byte_index in range(2):
            value = 0
            for bit in range(8):
                column = byte_index * 8 + bit
                if image.getpixel((column, row)):
                    value |= 0x80 >> bit
            output.append(value)
    return output


def main() -> None:
    unique_characters = "".join(dict.fromkeys(CHARACTERS))
    string_literal_pattern = re.compile(r'"(?:\\.|[^"\\])*"')
    used_characters: set[str] = set()
    for source_name in ("display_task.c", "cloud_task.c"):
        source = (OUTPUT_PATH.parent / source_name).read_text(encoding="utf-8")
        for literal in string_literal_pattern.findall(source):
            used_characters.update(
                character for character in literal if ord(character) > 0x7F
            )
    missing_characters = used_characters.difference(unique_characters)
    if missing_characters:
        missing = "".join(sorted(missing_characters, key=ord))
        raise SystemExit(f"Missing Chinese glyphs: {missing}")

    lines = [
        "/* Generated by tools/generate_chinese_font.py. */",
        "#ifndef CHINESE_FONT_16_H",
        "#define CHINESE_FONT_16_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    uint32_t codepoint;",
        "    uint8_t bitmap[32];",
        "} chinese_glyph_16_t;",
        "",
        "static const chinese_glyph_16_t chinese_glyphs_16[] = {",
    ]

    for character in sorted(unique_characters, key=ord):
        bitmap = glyph_bitmap(character)
        rows = ", ".join(f"0x{value:02X}" for value in bitmap)
        lines.append(
            f"    {{0x{ord(character):04X}, {{{rows}}}}}, /* {character} */"
        )

    lines.extend(
        [
            "};",
            "",
            "#define CHINESE_GLYPHS_16_COUNT \\",
            "    (sizeof(chinese_glyphs_16) / sizeof(chinese_glyphs_16[0]))",
            "",
            "#endif",
            "",
        ]
    )
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
